version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    expose:
      - "9092/tcp"

  angularnginx:
    container_name: angularnginx
    build:
        dockerfile: ./hpeml-front/Dockerfile
        context: .
    image: nginx
    depends_on:
      - pythonbackendff
    ports:
        - "80:80"
    expose: 
        - "80/tcp"

  pythonbackendff:
    container_name: pythonbackendff
    build:
        dockerfile: ./backendff/Dockerfile
        context: .
    command: python main.py
    depends_on:
      - angularnginx
    volumes:
      - .:/codebackendff
    ports:
      - "8000:8000"
    depends_on:
      - broker
      
  pythonservices:
    container_name: pythonservices
    build:
        dockerfile: ./services/Dockerfile
        context: .
    command: python main.py
    volumes:
      - .:/codeservices
    depends_on:
      - broker
      - dbmysqlexams
    env_file:
      - .env
      
  pythonautoexam:
    container_name: pythonautoexam
    build:
        dockerfile: ./autoexam/Dockerfile
        context: .
    command: python main.py
    volumes:
      - .:/codeautoexam
    depends_on:
      - broker

  dbmysqlexams:
    container_name: dbmysqlexams
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ctg
      MYSQL_USER: ctguser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./dbexam/initdb.sql:/docker-entrypoint-initdb.d/init.sql